services:
  - type: web
    name: trust-agreement-customizer
    runtime: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production

